#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   Issue #350 is still open: on Windows, the code here causes it to link
   with PYTHON36.DLL (for example) instead of PYTHON3.DLL.  A fix was
   attempted in 164e526a5515 and 14ce6985e1c3, but reverted: virtualenv
   does not make PYTHON3.DLL available, and so the "correctly" compiled
   version would not run inside a virtualenv.  We will re-apply the fix
   after virtualenv has been fixed for some time.  For explanation, see
   issue #355.  For a workaround if you want PYTHON3.DLL and don't worry
   about virtualenv, see issue #350.  See also 'py_limited_api' in
   setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  include <pyconfig.h>
#  if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG)
#    define Py_LIMITED_API
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t(x);
}


/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/

#include "char_concatenation.h"
#include "cursor_dependent_selection.h"
#include "cursor_move.h"
#include "debug.h"
#include "display.h"
#include "edition.h"
#include "newline_keypress.h"
#include "prompt.h"
#include "prompt_field.h"
#include "screen_size.h"
#include "shell_setup.h"
#include "t_caps_utils.h"
#include "t_char_insert.h"
#include "t_char_utils.h"
#include "t_cursor_utils.h"
#include "t_line_utils.h"
#include "termios_setter.h"
#include "libft.h"
#include "history.h"
#include "aaa.h"


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char *()(char *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 26), // char *
/*  2 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  3 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char *()(t_char *, t_cursor *, int)
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 136), // t_char *
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 137), // t_cursor *
/*  6 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/*  7 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION, 1), // char *()(void)
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 10 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(char *)
/* 11 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 12 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 13 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(int)
/* 14 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 15 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 16 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_caps * *)
/* 17 */ _CFFI_OP(_CFFI_OP_POINTER, 134), // t_caps * *
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 19 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char * *, char *, int)
/* 20 */ _CFFI_OP(_CFFI_OP_POINTER, 4), // t_char * *
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 22 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 23 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 24 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char * *, char, int)
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 26 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 27 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 28 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 29 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char * *, char, int, int)
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 31 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2),
/* 32 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 33 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 34 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char * *, int)
/* 36 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 38 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 39 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char * *, t_cursor *)
/* 40 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 41 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 42 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 43 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_char *)
/* 44 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 45 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 46 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_cursor * *)
/* 47 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // t_cursor * *
/* 48 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 49 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_cursor * *, int)
/* 50 */ _CFFI_OP(_CFFI_OP_NOOP, 47),
/* 51 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 52 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 53 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_hist * *)
/* 54 */ _CFFI_OP(_CFFI_OP_POINTER, 138), // t_hist * *
/* 55 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 56 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line * *)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 68), // t_line * *
/* 58 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 59 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line * *, int)
/* 60 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 61 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 62 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 63 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line * *, t_cursor * *)
/* 64 */ _CFFI_OP(_CFFI_OP_NOOP, 57),
/* 65 */ _CFFI_OP(_CFFI_OP_NOOP, 47),
/* 66 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 67 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line *)
/* 68 */ _CFFI_OP(_CFFI_OP_POINTER, 140), // t_line *
/* 69 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 70 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line *, char, t_cursor *)
/* 71 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 72 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2),
/* 73 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 74 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 75 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line *, t_cursor *)
/* 76 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 77 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 78 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 79 */ _CFFI_OP(_CFFI_OP_FUNCTION, 6), // int()(t_line *, t_cursor *, int)
/* 80 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 81 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 82 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 83 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 84 */ _CFFI_OP(_CFFI_OP_FUNCTION, 68), // t_line *()(t_line *)
/* 85 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 86 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 87 */ _CFFI_OP(_CFFI_OP_FUNCTION, 68), // t_line *()(t_line *, t_cursor *)
/* 88 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 89 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 90 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 91 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(char)
/* 92 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2),
/* 93 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 94 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_char * *)
/* 95 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 96 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 97 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_char *)
/* 98 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 99 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 100 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_char *, int)
/* 101 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 102 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 103 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 104 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_char *, t_cursor *, int, int *)
/* 105 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 106 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 107 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 108 */ _CFFI_OP(_CFFI_OP_POINTER, 6), // int *
/* 109 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 110 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_cursor *, t_char * *, t_char * *)
/* 111 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 112 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 113 */ _CFFI_OP(_CFFI_OP_NOOP, 20),
/* 114 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 115 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_line *, char *, t_cursor *)
/* 116 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 117 */ _CFFI_OP(_CFFI_OP_NOOP, 1),
/* 118 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 119 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 120 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_line *, int)
/* 121 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 122 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 123 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 124 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_line *, int, t_cursor *)
/* 125 */ _CFFI_OP(_CFFI_OP_NOOP, 68),
/* 126 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7),
/* 127 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 128 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 129 */ _CFFI_OP(_CFFI_OP_FUNCTION, 142), // void()(t_win *)
/* 130 */ _CFFI_OP(_CFFI_OP_POINTER, 141), // t_win *
/* 131 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 132 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // enum malloc_fail
/* 133 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 5), // short
/* 134 */ _CFFI_OP(_CFFI_OP_POINTER, 135), // t_caps *
/* 135 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // t_caps
/* 136 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 2), // t_char
/* 137 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // t_cursor
/* 138 */ _CFFI_OP(_CFFI_OP_POINTER, 139), // t_hist *
/* 139 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 3), // t_hist
/* 140 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 4), // t_line
/* 141 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 5), // t_win
/* 142 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

_CFFI_UNUSED_FN
static void _cffi_checkfld_typedef_t_cursor(t_cursor *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->row) | 0);  /* check that 't_cursor.row' is an integer */
  (void)((p->column) | 0);  /* check that 't_cursor.column' is an integer */
}
struct _cffi_align_typedef_t_cursor { char x; t_cursor y; };

static int _cffi_const_MALLOC_ERROR(unsigned long long *o)
{
  int n = (MALLOC_ERROR) <= 0;
  *o = (unsigned long long)((MALLOC_ERROR) | 0);  /* check that MALLOC_ERROR is an integer */
  return n;
}

static int _cffi_const_MALLOC_SUCCESS(unsigned long long *o)
{
  int n = (MALLOC_SUCCESS) <= 0;
  *o = (unsigned long long)((MALLOC_SUCCESS) | 0);  /* check that MALLOC_SUCCESS is an integer */
  return n;
}

static void _cffi_d_DEBUG_print_char(t_char * x0, int x1)
{
  DEBUG_print_char(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_DEBUG_print_char(PyObject *self, PyObject *args)
{
  t_char * x0;
  int x1;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "DEBUG_print_char", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { DEBUG_print_char(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_DEBUG_print_char _cffi_d_DEBUG_print_char
#endif

static void _cffi_d_DEBUG_print_line(t_line * x0, int x1)
{
  DEBUG_print_line(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_DEBUG_print_line(PyObject *self, PyObject *args)
{
  t_line * x0;
  int x1;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "DEBUG_print_line", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { DEBUG_print_line(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_DEBUG_print_line _cffi_d_DEBUG_print_line
#endif

static char * _cffi_d_add_cwd(void)
{
  return add_cwd();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_add_cwd(PyObject *self, PyObject *noarg)
{
  char * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = add_cwd(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_add_cwd _cffi_d_add_cwd
#endif

static char * _cffi_d_add_date(void)
{
  return add_date();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_add_date(PyObject *self, PyObject *noarg)
{
  char * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = add_date(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_add_date _cffi_d_add_date
#endif

static char * _cffi_d_add_user(void)
{
  return add_user();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_add_user(PyObject *self, PyObject *noarg)
{
  char * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = add_user(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_add_user _cffi_d_add_user
#endif

static int _cffi_d_alloc_capabilities_struct(t_caps * * x0)
{
  return alloc_capabilities_struct(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_alloc_capabilities_struct(PyObject *self, PyObject *arg0)
{
  t_caps * * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(17), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_caps * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(17), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = alloc_capabilities_struct(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_alloc_capabilities_struct _cffi_d_alloc_capabilities_struct
#endif

static int _cffi_d_alloc_cursor(t_cursor * * x0)
{
  return alloc_cursor(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_alloc_cursor(PyObject *self, PyObject *arg0)
{
  t_cursor * * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(47), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_cursor * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(47), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = alloc_cursor(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_alloc_cursor _cffi_d_alloc_cursor
#endif

static int _cffi_d_char_lock_len(t_char * x0)
{
  return char_lock_len(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_char_lock_len(PyObject *self, PyObject *arg0)
{
  t_char * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = char_lock_len(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_char_lock_len _cffi_d_char_lock_len
#endif

static int _cffi_d_char_lst_len(t_char * x0)
{
  return char_lst_len(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_char_lst_len(PyObject *self, PyObject *arg0)
{
  t_char * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = char_lst_len(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_char_lst_len _cffi_d_char_lst_len
#endif

static int _cffi_d_create_char(t_char * * x0, char x1, int x2, int x3)
{
  return create_char(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_create_char(PyObject *self, PyObject *args)
{
  t_char * * x0;
  char x1;
  int x2;
  int x3;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "create_char", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  x1 = (char)_cffi_to_c_char(arg1);
  if (x1 == (char)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  x3 = _cffi_to_c_int(arg3, int);
  if (x3 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = create_char(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_create_char _cffi_d_create_char
#endif

static int _cffi_d_create_t_line(t_line * * x0, int x1)
{
  return create_t_line(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_create_t_line(PyObject *self, PyObject *args)
{
  t_line * * x0;
  int x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "create_t_line", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(57), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = create_t_line(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_create_t_line _cffi_d_create_t_line
#endif

static int _cffi_d_dealloc_cursor(t_cursor * * x0, int x1)
{
  return dealloc_cursor(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_dealloc_cursor(PyObject *self, PyObject *args)
{
  t_cursor * * x0;
  int x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "dealloc_cursor", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(47), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_cursor * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(47), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = dealloc_cursor(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_dealloc_cursor _cffi_d_dealloc_cursor
#endif

static int _cffi_d_del_pos_char(t_char * * x0, t_cursor * x1)
{
  return del_pos_char(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_del_pos_char(PyObject *self, PyObject *args)
{
  t_char * * x0;
  t_cursor * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "del_pos_char", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = del_pos_char(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_del_pos_char _cffi_d_del_pos_char
#endif

static int _cffi_d_delete_char(t_line * x0, t_cursor * x1)
{
  return delete_char(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_delete_char(PyObject *self, PyObject *args)
{
  t_line * x0;
  t_cursor * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "delete_char", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = delete_char(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_delete_char _cffi_d_delete_char
#endif

static void _cffi_d_display_chars(t_char * x0, t_cursor * x1, int x2, int * x3)
{
  display_chars(x0, x1, x2, x3);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_display_chars(PyObject *self, PyObject *args)
{
  t_char * x0;
  t_cursor * x1;
  int x2;
  int * x3;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;
  PyObject *arg3;

  if (!PyArg_UnpackTuple(args, "display_chars", 4, 4, &arg0, &arg1, &arg2, &arg3))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(108), arg3, (char **)&x3);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x3 = (int *)alloca((size_t)datasize);
    memset((void *)x3, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x3, _cffi_type(108), arg3) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { display_chars(x0, x1, x2, x3); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_display_chars _cffi_d_display_chars
#endif

static int _cffi_d_display_shell(t_line * x0, t_cursor * x1, int x2)
{
  return display_shell(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_display_shell(PyObject *self, PyObject *args)
{
  t_line * x0;
  t_cursor * x1;
  int x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "display_shell", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = display_shell(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_display_shell _cffi_d_display_shell
#endif

static void _cffi_d_fdelete_line(t_line * x0, int x1, t_cursor * x2)
{
  fdelete_line(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_fdelete_line(PyObject *self, PyObject *args)
{
  t_line * x0;
  int x1;
  t_cursor * x2;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "fdelete_line", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(5), arg2) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { fdelete_line(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_fdelete_line _cffi_d_fdelete_line
#endif

static int _cffi_d_file_size(char * x0)
{
  return file_size(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_file_size(PyObject *self, PyObject *arg0)
{
  char * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = file_size(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_file_size _cffi_d_file_size
#endif

static char * _cffi_d_format_char_lst(t_char * x0, t_cursor * x1, int x2)
{
  return format_char_lst(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_format_char_lst(PyObject *self, PyObject *args)
{
  t_char * x0;
  t_cursor * x1;
  int x2;
  Py_ssize_t datasize;
  char * result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "format_char_lst", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = format_char_lst(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_format_char_lst _cffi_d_format_char_lst
#endif

static char * _cffi_d_format_prompt(void)
{
  return format_prompt();
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_format_prompt(PyObject *self, PyObject *noarg)
{
  char * result;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = format_prompt(); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  (void)noarg; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_format_prompt _cffi_d_format_prompt
#endif

static void _cffi_d_free_t_char(t_char * * x0)
{
  free_t_char(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_t_char(PyObject *self, PyObject *arg0)
{
  t_char * * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { free_t_char(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_free_t_char _cffi_d_free_t_char
#endif

static int _cffi_d_free_t_char_lst(t_char * * x0, int x1)
{
  return free_t_char_lst(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_t_char_lst(PyObject *self, PyObject *args)
{
  t_char * * x0;
  int x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "free_t_char_lst", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = free_t_char_lst(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_free_t_char_lst _cffi_d_free_t_char_lst
#endif

static int _cffi_d_free_t_line(t_line * * x0, int x1)
{
  return free_t_line(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_t_line(PyObject *self, PyObject *args)
{
  t_line * * x0;
  int x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "free_t_line", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(57), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = free_t_line(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_free_t_line _cffi_d_free_t_line
#endif

static int _cffi_d_free_t_line_lst(t_line * * x0, int x1)
{
  return free_t_line_lst(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_free_t_line_lst(PyObject *self, PyObject *args)
{
  t_line * * x0;
  int x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "free_t_line_lst", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(57), arg0) < 0)
      return NULL;
  }

  x1 = _cffi_to_c_int(arg1, int);
  if (x1 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = free_t_line_lst(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_free_t_line_lst _cffi_d_free_t_line_lst
#endif

static void _cffi_d_get_cursor_char(t_cursor * x0, t_char * * x1, t_char * * x2)
{
  get_cursor_char(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_get_cursor_char(PyObject *self, PyObject *args)
{
  t_cursor * x0;
  t_char * * x1;
  t_char * * x2;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "get_cursor_char", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(5), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(20), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(20), arg2) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { get_cursor_char(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_get_cursor_char _cffi_d_get_cursor_char
#endif

static t_line * _cffi_d_get_cursor_line(t_line * x0, t_cursor * x1)
{
  return get_cursor_line(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_get_cursor_line(PyObject *self, PyObject *args)
{
  t_line * x0;
  t_cursor * x1;
  Py_ssize_t datasize;
  t_line * result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "get_cursor_line", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = get_cursor_line(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(68));
}
#else
#  define _cffi_f_get_cursor_line _cffi_d_get_cursor_line
#endif

static t_line * _cffi_d_get_last_line(t_line * x0)
{
  return get_last_line(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_get_last_line(PyObject *self, PyObject *arg0)
{
  t_line * x0;
  Py_ssize_t datasize;
  t_line * result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = get_last_line(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(68));
}
#else
#  define _cffi_f_get_last_line _cffi_d_get_last_line
#endif

static int _cffi_d_insert_char(t_line * x0, char x1, t_cursor * x2)
{
  return insert_char(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_insert_char(PyObject *self, PyObject *args)
{
  t_line * x0;
  char x1;
  t_cursor * x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "insert_char", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  x1 = (char)_cffi_to_c_char(arg1);
  if (x1 == (char)-1 && PyErr_Occurred())
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(5), arg2) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = insert_char(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_insert_char _cffi_d_insert_char
#endif

static int _cffi_d_insert_string(t_char * * x0, char * x1, int x2)
{
  return insert_string(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_insert_string(PyObject *self, PyObject *args)
{
  t_char * * x0;
  char * x1;
  int x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "insert_string", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(1), arg1) < 0)
      return NULL;
  }

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = insert_string(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_insert_string _cffi_d_insert_string
#endif

static int _cffi_d_is_cursor_last_pos(t_line * x0, t_cursor * x1)
{
  return is_cursor_last_pos(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_is_cursor_last_pos(PyObject *self, PyObject *args)
{
  t_line * x0;
  t_cursor * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "is_cursor_last_pos", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = is_cursor_last_pos(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_is_cursor_last_pos _cffi_d_is_cursor_last_pos
#endif

static int _cffi_d_is_key_movement(char * x0)
{
  return is_key_movement(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_is_key_movement(PyObject *self, PyObject *arg0)
{
  char * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = is_key_movement(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_is_key_movement _cffi_d_is_key_movement
#endif

static int _cffi_d_line_lst_len(t_line * x0)
{
  return line_lst_len(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_line_lst_len(PyObject *self, PyObject *arg0)
{
  t_line * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = line_lst_len(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_line_lst_len _cffi_d_line_lst_len
#endif

static int _cffi_d_manage_termios(int x0)
{
  return manage_termios(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_manage_termios(PyObject *self, PyObject *arg0)
{
  int x0;
  int result;

  x0 = _cffi_to_c_int(arg0, int);
  if (x0 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = manage_termios(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_manage_termios _cffi_d_manage_termios
#endif

static int _cffi_d_newline_check(t_line * x0, t_cursor * x1)
{
  return newline_check(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_newline_check(PyObject *self, PyObject *args)
{
  t_line * x0;
  t_cursor * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "newline_check", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(5), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = newline_check(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_newline_check _cffi_d_newline_check
#endif

static int _cffi_d_push_end_char(t_char * * x0, char x1, int x2)
{
  return push_end_char(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_push_end_char(PyObject *self, PyObject *args)
{
  t_char * * x0;
  char x1;
  int x2;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "push_end_char", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(20), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(20), arg0) < 0)
      return NULL;
  }

  x1 = (char)_cffi_to_c_char(arg1);
  if (x1 == (char)-1 && PyErr_Occurred())
    return NULL;

  x2 = _cffi_to_c_int(arg2, int);
  if (x2 == (int)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = push_end_char(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_push_end_char _cffi_d_push_end_char
#endif

static int _cffi_d_push_end_line(t_line * * x0)
{
  return push_end_line(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_push_end_line(PyObject *self, PyObject *arg0)
{
  t_line * * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(57), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = push_end_line(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_push_end_line _cffi_d_push_end_line
#endif

static char * _cffi_d_replace_home(char * x0)
{
  return replace_home(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_replace_home(PyObject *self, PyObject *arg0)
{
  char * x0;
  Py_ssize_t datasize;
  char * result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(1), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = replace_home(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_pointer((char *)result, _cffi_type(1));
}
#else
#  define _cffi_f_replace_home _cffi_d_replace_home
#endif

static void _cffi_d_screen_size(t_win * x0)
{
  screen_size(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_screen_size(PyObject *self, PyObject *arg0)
{
  t_win * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(130), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_win *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(130), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { screen_size(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_screen_size _cffi_d_screen_size
#endif

static int _cffi_d_shell_preconfig(t_line * * x0, t_cursor * * x1)
{
  return shell_preconfig(x0, x1);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_shell_preconfig(PyObject *self, PyObject *args)
{
  t_line * * x0;
  t_cursor * * x1;
  Py_ssize_t datasize;
  int result;
  PyObject *arg0;
  PyObject *arg1;

  if (!PyArg_UnpackTuple(args, "shell_preconfig", 2, 2, &arg0, &arg1))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(57), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(57), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(47), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (t_cursor * *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(47), arg1) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = shell_preconfig(x0, x1); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_shell_preconfig _cffi_d_shell_preconfig
#endif

static void _cffi_d_show_cursor(char x0)
{
  show_cursor(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_show_cursor(PyObject *self, PyObject *arg0)
{
  char x0;

  x0 = (char)_cffi_to_c_char(arg0);
  if (x0 == (char)-1 && PyErr_Occurred())
    return NULL;

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { show_cursor(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_show_cursor _cffi_d_show_cursor
#endif

static void _cffi_d_simple_cursor_move(t_line * x0, char * x1, t_cursor * x2)
{
  simple_cursor_move(x0, x1, x2);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_simple_cursor_move(PyObject *self, PyObject *args)
{
  t_line * x0;
  char * x1;
  t_cursor * x2;
  Py_ssize_t datasize;
  PyObject *arg0;
  PyObject *arg1;
  PyObject *arg2;

  if (!PyArg_UnpackTuple(args, "simple_cursor_move", 3, 3, &arg0, &arg1, &arg2))
    return NULL;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(68), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_line *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(68), arg0) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(1), arg1, (char **)&x1);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x1 = (char *)alloca((size_t)datasize);
    memset((void *)x1, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x1, _cffi_type(1), arg1) < 0)
      return NULL;
  }

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(5), arg2, (char **)&x2);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x2 = (t_cursor *)alloca((size_t)datasize);
    memset((void *)x2, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x2, _cffi_type(5), arg2) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { simple_cursor_move(x0, x1, x2); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_simple_cursor_move _cffi_d_simple_cursor_move
#endif

static int _cffi_d_store_history(t_hist * * x0)
{
  return store_history(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_store_history(PyObject *self, PyObject *arg0)
{
  t_hist * * x0;
  Py_ssize_t datasize;
  int result;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(54), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_hist * *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(54), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { result = store_history(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  return _cffi_from_c_int(result, int);
}
#else
#  define _cffi_f_store_history _cffi_d_store_history
#endif

static void _cffi_d_update_position(t_char * x0)
{
  update_position(x0);
}
#ifndef PYPY_VERSION
static PyObject *
_cffi_f_update_position(PyObject *self, PyObject *arg0)
{
  t_char * x0;
  Py_ssize_t datasize;

  datasize = _cffi_prepare_pointer_call_argument(
      _cffi_type(4), arg0, (char **)&x0);
  if (datasize != 0) {
    if (datasize < 0)
      return NULL;
    x0 = (t_char *)alloca((size_t)datasize);
    memset((void *)x0, 0, (size_t)datasize);
    if (_cffi_convert_array_from_object((char *)x0, _cffi_type(4), arg0) < 0)
      return NULL;
  }

  Py_BEGIN_ALLOW_THREADS
  _cffi_restore_errno();
  { update_position(x0); }
  _cffi_save_errno();
  Py_END_ALLOW_THREADS

  (void)self; /* unused */
  Py_INCREF(Py_None);
  return Py_None;
}
#else
#  define _cffi_f_update_position _cffi_d_update_position
#endif

_CFFI_UNUSED_FN
static void _cffi_checkfld__t_caps(t_caps *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char * *tmp = &p->clear; (void)tmp; }
  { char * *tmp = &p->video; (void)tmp; }
  { char * *tmp = &p->reset_video; (void)tmp; }
  { char * *tmp = &p->hide_cursor; (void)tmp; }
  { char * *tmp = &p->reset_cursor; (void)tmp; }
  { char * *tmp = &p->save_pos; (void)tmp; }
  { char * *tmp = &p->reset_pos; (void)tmp; }
  { char * *tmp = &p->del_line; (void)tmp; }
  { char * *tmp = &p->start_line; (void)tmp; }
  { char * *tmp = &p->move_up; (void)tmp; }
  { char * *tmp = &p->move_down; (void)tmp; }
}
struct _cffi_align__t_caps { char x; t_caps y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__t_char(t_char *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char *tmp = &p->letter; (void)tmp; }
  (void)((p->lock) | 0);  /* check that 't_char.lock' is an integer */
  (void)((p->position) | 0);  /* check that 't_char.position' is an integer */
  { t_char * *tmp = &p->next; (void)tmp; }
}
struct _cffi_align__t_char { char x; t_char y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__t_hist(t_hist *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char * *tmp = &p->line; (void)tmp; }
  { t_hist * *tmp = &p->next; (void)tmp; }
  { t_hist * *tmp = &p->prev; (void)tmp; }
}
struct _cffi_align__t_hist { char x; t_hist y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__t_line(t_line *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  (void)((p->position) | 0);  /* check that 't_line.position' is an integer */
  { t_char * *tmp = &p->chars; (void)tmp; }
  { t_line * *tmp = &p->next; (void)tmp; }
}
struct _cffi_align__t_line { char x; t_line y; };

static int *_cffi_var_fd_debug(void)
{
  return &(fd_debug);
}

static t_caps * *_cffi_var_g_caps(void)
{
  return &(g_caps);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "DEBUG_print_char", (void *)_cffi_f_DEBUG_print_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 100), (void *)_cffi_d_DEBUG_print_char },
  { "DEBUG_print_line", (void *)_cffi_f_DEBUG_print_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 120), (void *)_cffi_d_DEBUG_print_line },
  { "MALLOC_ERROR", (void *)_cffi_const_MALLOC_ERROR, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "MALLOC_SUCCESS", (void *)_cffi_const_MALLOC_SUCCESS, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "add_cwd", (void *)_cffi_f_add_cwd, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 8), (void *)_cffi_d_add_cwd },
  { "add_date", (void *)_cffi_f_add_date, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 8), (void *)_cffi_d_add_date },
  { "add_user", (void *)_cffi_f_add_user, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 8), (void *)_cffi_d_add_user },
  { "alloc_capabilities_struct", (void *)_cffi_f_alloc_capabilities_struct, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 16), (void *)_cffi_d_alloc_capabilities_struct },
  { "alloc_cursor", (void *)_cffi_f_alloc_cursor, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 46), (void *)_cffi_d_alloc_cursor },
  { "char_lock_len", (void *)_cffi_f_char_lock_len, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 43), (void *)_cffi_d_char_lock_len },
  { "char_lst_len", (void *)_cffi_f_char_lst_len, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 43), (void *)_cffi_d_char_lst_len },
  { "create_char", (void *)_cffi_f_create_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 29), (void *)_cffi_d_create_char },
  { "create_t_line", (void *)_cffi_f_create_t_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 59), (void *)_cffi_d_create_t_line },
  { "dealloc_cursor", (void *)_cffi_f_dealloc_cursor, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 49), (void *)_cffi_d_dealloc_cursor },
  { "del_pos_char", (void *)_cffi_f_del_pos_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 39), (void *)_cffi_d_del_pos_char },
  { "delete_char", (void *)_cffi_f_delete_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 75), (void *)_cffi_d_delete_char },
  { "display_chars", (void *)_cffi_f_display_chars, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 104), (void *)_cffi_d_display_chars },
  { "display_shell", (void *)_cffi_f_display_shell, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 79), (void *)_cffi_d_display_shell },
  { "fd_debug", (void *)_cffi_var_fd_debug, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 6), (void *)0 },
  { "fdelete_line", (void *)_cffi_f_fdelete_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 124), (void *)_cffi_d_fdelete_line },
  { "file_size", (void *)_cffi_f_file_size, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 10), (void *)_cffi_d_file_size },
  { "format_char_lst", (void *)_cffi_f_format_char_lst, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 3), (void *)_cffi_d_format_char_lst },
  { "format_prompt", (void *)_cffi_f_format_prompt, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_N, 8), (void *)_cffi_d_format_prompt },
  { "free_t_char", (void *)_cffi_f_free_t_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 94), (void *)_cffi_d_free_t_char },
  { "free_t_char_lst", (void *)_cffi_f_free_t_char_lst, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 35), (void *)_cffi_d_free_t_char_lst },
  { "free_t_line", (void *)_cffi_f_free_t_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 59), (void *)_cffi_d_free_t_line },
  { "free_t_line_lst", (void *)_cffi_f_free_t_line_lst, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 59), (void *)_cffi_d_free_t_line_lst },
  { "g_caps", (void *)_cffi_var_g_caps, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 134), (void *)0 },
  { "get_cursor_char", (void *)_cffi_f_get_cursor_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 110), (void *)_cffi_d_get_cursor_char },
  { "get_cursor_line", (void *)_cffi_f_get_cursor_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 87), (void *)_cffi_d_get_cursor_line },
  { "get_last_line", (void *)_cffi_f_get_last_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 84), (void *)_cffi_d_get_last_line },
  { "insert_char", (void *)_cffi_f_insert_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 70), (void *)_cffi_d_insert_char },
  { "insert_string", (void *)_cffi_f_insert_string, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 19), (void *)_cffi_d_insert_string },
  { "is_cursor_last_pos", (void *)_cffi_f_is_cursor_last_pos, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 75), (void *)_cffi_d_is_cursor_last_pos },
  { "is_key_movement", (void *)_cffi_f_is_key_movement, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 10), (void *)_cffi_d_is_key_movement },
  { "line_lst_len", (void *)_cffi_f_line_lst_len, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 67), (void *)_cffi_d_line_lst_len },
  { "manage_termios", (void *)_cffi_f_manage_termios, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 13), (void *)_cffi_d_manage_termios },
  { "newline_check", (void *)_cffi_f_newline_check, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 75), (void *)_cffi_d_newline_check },
  { "push_end_char", (void *)_cffi_f_push_end_char, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 24), (void *)_cffi_d_push_end_char },
  { "push_end_line", (void *)_cffi_f_push_end_line, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 56), (void *)_cffi_d_push_end_line },
  { "replace_home", (void *)_cffi_f_replace_home, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 0), (void *)_cffi_d_replace_home },
  { "screen_size", (void *)_cffi_f_screen_size, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 129), (void *)_cffi_d_screen_size },
  { "shell_preconfig", (void *)_cffi_f_shell_preconfig, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 63), (void *)_cffi_d_shell_preconfig },
  { "show_cursor", (void *)_cffi_f_show_cursor, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 91), (void *)_cffi_d_show_cursor },
  { "simple_cursor_move", (void *)_cffi_f_simple_cursor_move, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_V, 115), (void *)_cffi_d_simple_cursor_move },
  { "store_history", (void *)_cffi_f_store_history, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 53), (void *)_cffi_d_store_history },
  { "update_position", (void *)_cffi_f_update_position, _CFFI_OP(_CFFI_OP_CPYTHON_BLTN_O, 97), (void *)_cffi_d_update_position },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "row", offsetof(t_cursor, row),
           sizeof(((t_cursor *)0)->row),
           _CFFI_OP(_CFFI_OP_NOOP, 133) },
  { "column", offsetof(t_cursor, column),
              sizeof(((t_cursor *)0)->column),
              _CFFI_OP(_CFFI_OP_NOOP, 133) },
  { "clear", offsetof(t_caps, clear),
             sizeof(((t_caps *)0)->clear),
             _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "video", offsetof(t_caps, video),
             sizeof(((t_caps *)0)->video),
             _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "reset_video", offsetof(t_caps, reset_video),
                   sizeof(((t_caps *)0)->reset_video),
                   _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "hide_cursor", offsetof(t_caps, hide_cursor),
                   sizeof(((t_caps *)0)->hide_cursor),
                   _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "reset_cursor", offsetof(t_caps, reset_cursor),
                    sizeof(((t_caps *)0)->reset_cursor),
                    _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "save_pos", offsetof(t_caps, save_pos),
                sizeof(((t_caps *)0)->save_pos),
                _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "reset_pos", offsetof(t_caps, reset_pos),
                 sizeof(((t_caps *)0)->reset_pos),
                 _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "del_line", offsetof(t_caps, del_line),
                sizeof(((t_caps *)0)->del_line),
                _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "start_line", offsetof(t_caps, start_line),
                  sizeof(((t_caps *)0)->start_line),
                  _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "move_up", offsetof(t_caps, move_up),
               sizeof(((t_caps *)0)->move_up),
               _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "move_down", offsetof(t_caps, move_down),
                 sizeof(((t_caps *)0)->move_down),
                 _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "letter", offsetof(t_char, letter),
              sizeof(((t_char *)0)->letter),
              _CFFI_OP(_CFFI_OP_NOOP, 26) },
  { "lock", (size_t)-1,
            2 /* bits */,
            _CFFI_OP(_CFFI_OP_BITFIELD, 133) },
  { "position", offsetof(t_char, position),
                sizeof(((t_char *)0)->position),
                _CFFI_OP(_CFFI_OP_NOOP, 133) },
  { "next", offsetof(t_char, next),
            sizeof(((t_char *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "line", offsetof(t_hist, line),
            sizeof(((t_hist *)0)->line),
            _CFFI_OP(_CFFI_OP_NOOP, 1) },
  { "next", offsetof(t_hist, next),
            sizeof(((t_hist *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 138) },
  { "prev", offsetof(t_hist, prev),
            sizeof(((t_hist *)0)->prev),
            _CFFI_OP(_CFFI_OP_NOOP, 138) },
  { "position", offsetof(t_line, position),
                sizeof(((t_line *)0)->position),
                _CFFI_OP(_CFFI_OP_NOOP, 6) },
  { "chars", offsetof(t_line, chars),
             sizeof(((t_line *)0)->chars),
             _CFFI_OP(_CFFI_OP_NOOP, 4) },
  { "next", offsetof(t_line, next),
            sizeof(((t_line *)0)->next),
            _CFFI_OP(_CFFI_OP_NOOP, 68) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "$t_cursor", 137, _CFFI_F_CHECK_FIELDS,
    sizeof(t_cursor), offsetof(struct _cffi_align_typedef_t_cursor, y), 0, 2 },
  { "s_caps", 135, _CFFI_F_CHECK_FIELDS,
    sizeof(t_caps), offsetof(struct _cffi_align__t_caps, y), 2, 11 },
  { "s_char", 136, _CFFI_F_CHECK_FIELDS,
    sizeof(t_char), offsetof(struct _cffi_align__t_char, y), 13, 4 },
  { "s_hist", 139, _CFFI_F_CHECK_FIELDS,
    sizeof(t_hist), offsetof(struct _cffi_align__t_hist, y), 17, 3 },
  { "s_line", 140, _CFFI_F_CHECK_FIELDS,
    sizeof(t_line), offsetof(struct _cffi_align__t_line, y), 20, 3 },
  { "winsize", 141, _CFFI_F_OPAQUE,
    (size_t)-1, -1, -1, 0 /* opaque */ },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "malloc_fail", 132, _cffi_prim_int(sizeof(enum malloc_fail), ((enum malloc_fail)-1) <= 0),
    "MALLOC_ERROR,MALLOC_SUCCESS" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "t_caps", 135 },
  { "t_char", 136 },
  { "t_cursor", 137 },
  { "t_hist", 139 },
  { "t_line", 140 },
  { "t_win", 141 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  47,  /* num_globals */
  6,  /* num_struct_unions */
  1,  /* num_enums */
  6,  /* num_typenames */
  NULL,  /* no includes */
  143,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_ProjectFuncCffi(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_ProjectFuncCffi(void) { return NULL; }
#  else
     initProjectFuncCffi(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_ProjectFuncCffi(void)
{
  return _cffi_init("unittest.ProjectFuncCffi", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initProjectFuncCffi(void)
{
  _cffi_init("unittest.ProjectFuncCffi", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
